version: '3'

services:
  # Nginx container
  webserver:
    build:
      context: https://github.com/ploschka/nginx-symfony.git
      dockerfile: nginx.Dockerfile
    container_name: webserver
    volumes:
      - ./:/app:ro
    ports:
      - 8080:80    
    networks:
      - app-network

  # PHP-fpm container
  app:
    build:
      context: https://github.com/ploschka/nginx-symfony.git
      dockerfile: php.Dockerfile
    container_name: app
    volumes:
      - ./:/app:rw
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-app}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-!ChangeMe!}
      MYSQL_USER: ${MYSQL_USER:-app}    
    networks:
      - app-network
    command: dev

  # MySQL container
###> doctrine/doctrine-bundle ###
  database:
    image: mysql:${MYSQL_VERSION:-8.0.31}
    container_name: mysql-database
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-app}
      # You should definitely change the password in production
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD:-!ChangeMe!}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-!ChangeMe!}
      MYSQL_USER: ${MYSQL_USER:-app}
    volumes:
      - db-data:/var/lib/mysql:rw
    networks:
      - app-network
###< doctrine/doctrine-bundle ###

networks:
  app-network:
    driver: bridge
volumes:
###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###
